### ISSUE TITLE
IBX-SDK Roadmap

### ISSUE THREAD

**Issue by yeti9990** [Infoblox-PS/ibx-sdk#1]
# IBX-SDK Roadmap for Initial Release

This contains our initial roadmap for the Infoblox Basic API Toolkit

Initial Release - 0.2.0
* [x] Refactor the WAPI class
* [x] All methods public & private MUST have docstring using Google format
* [x] Refactor all "private" methods from _method to __method i.e. double underscore
* [x] Remove Example code from any __private_methods 
* [x] Review / Refactor and update any all Exception Handling ensuring consistency
* [x] Find, Review and/or eliminate any Intellectual Property or IP information
* [x] Update / Refactor all script @click args to be consistent, properly formatted, typed, and implemented
* [x] Finalize LICENSE.md
* [x] Finalize `pyproject.toml` for uploading package into PyPi
* [x] Update docstrings, code samples, docs with refactoring of WAPI to Gift class
* [x] Develop unit and integration test(s)
* [x] Finalize README.md and any other supporting documentation such as HOWTOs and CLI usage
  * [x] Final review of the **Introduction** section of the WAPI docs
  * [x] Final review of the **Creating Objects** section of the docs
  * [x] Final review of the **Updating Objects** section of the docs
  * [x] Final review of the **Deleting Objects** section of the docs
  * [x] Final review of the **Calling Functions** section of the docs
  * [x] add more recipes to the **Cookbook** section
* [x] Perform package installation testing on *NIX, MAC OS, and Windows
  * [x] Windows 11
  * [x] Windows server 2012R2
  * [x] Windows WSL
  * [x] OSX Intel
  * [x] OSX M1
  * [x] Linux (Red Hat Variant & Ubuntu) 
* [x] Create 0.2.0 initial build w/ updated CHANGELOG.md
* [x] Push initial script to PyPI
* [x] Update Image on README.md
